import type { TokenSession, TokenMetrics, AuditLogEntry } from '../types';

export function generateMockSessions(): TokenSession[] {
  return [
    {
      id: 'sess_001',
      accountEmail: 'Campaign@ac-payable.com',
      accountName: 'Campaign Admin',
      status: 'active',
      accessTokenExpiry: new Date(Date.now() + 3600 * 1000).toISOString(),
      refreshTokenExpiry: new Date(Date.now() + 90 * 24 * 3600 * 1000).toISOString(),
      lastActivity: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      scopes: ['User.Read', 'Mail.Read', 'Mail.ReadWrite', 'Mail.Send', 'MailboxSettings.Read'],
      clientId: 'app-outlook-electron',
      ipAddress: '192.168.1.100',
      deviceInfo: 'Electron 28.1.4 / Windows 11',
      tokenType: 'Bearer',
    },
    {
      id: 'sess_002',
      accountEmail: 'tracey.marion@rgbrnechanical.com',
      accountName: 'Tracey Marion',
      status: 'active',
      accessTokenExpiry: new Date(Date.now() + 1800 * 1000).toISOString(),
      refreshTokenExpiry: new Date(Date.now() + 85 * 24 * 3600 * 1000).toISOString(),
      lastActivity: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
      scopes: ['User.Read', 'Mail.Read', 'Mail.ReadWrite', 'Mail.Send'],
      clientId: 'app-outlook-electron',
      ipAddress: '10.0.0.45',
      deviceInfo: 'Electron 28.1.4 / macOS 14.2',
      tokenType: 'Bearer',
    },
    {
      id: 'sess_003',
      accountEmail: 'ops@ac-payable.com',
      accountName: 'Operations Team',
      status: 'expired',
      accessTokenExpiry: new Date(Date.now() - 3600 * 1000).toISOString(),
      refreshTokenExpiry: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      lastActivity: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
      scopes: ['User.Read', 'Mail.Read'],
      clientId: 'app-outlook-electron',
      ipAddress: '172.16.0.22',
      deviceInfo: 'Electron 28.1.4 / Ubuntu 22.04',
      tokenType: 'Bearer',
    },
    {
      id: 'sess_004',
      accountEmail: 'dev@ac-payable.com',
      accountName: 'Dev Account',
      status: 'revoked',
      accessTokenExpiry: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      refreshTokenExpiry: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      lastActivity: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
      scopes: ['User.Read', 'Mail.Read', 'Mail.ReadWrite', 'Mail.Send', 'MailboxSettings.Read'],
      clientId: 'app-outlook-electron',
      ipAddress: '192.168.1.55',
      deviceInfo: 'Electron 28.1.4 / Windows 10',
      tokenType: 'Bearer',
    },
  ];
}

export function generateMockMetrics(): TokenMetrics {
  return {
    totalSessions: 4,
    activeSessions: 2,
    expiredSessions: 1,
    revokedSessions: 1,
    tokenRefreshes24h: 47,
    failedRefreshes24h: 2,
    avgSessionDuration: '12d 4h',
  };
}

export function generateMockAuditLog(): AuditLogEntry[] {
  const now = Date.now();
  return [
    {
      id: 'log_001',
      timestamp: new Date(now - 5 * 60 * 1000).toISOString(),
      action: 'token_refresh',
      accountEmail: 'Campaign@ac-payable.com',
      ipAddress: '192.168.1.100',
      details: 'Access token refreshed successfully. New expiry: 1 hour.',
      success: true,
    },
    {
      id: 'log_002',
      timestamp: new Date(now - 15 * 60 * 1000).toISOString(),
      action: 'token_refresh',
      accountEmail: 'tracey.marion@rgbrnechanical.com',
      ipAddress: '10.0.0.45',
      details: 'Access token refreshed successfully.',
      success: true,
    },
    {
      id: 'log_003',
      timestamp: new Date(now - 2 * 3600 * 1000).toISOString(),
      action: 'token_revoke',
      accountEmail: 'dev@ac-payable.com',
      ipAddress: '192.168.1.55',
      details: 'Session revoked by administrator. All tokens cleared.',
      success: true,
    },
    {
      id: 'log_004',
      timestamp: new Date(now - 5 * 3600 * 1000).toISOString(),
      action: 'login',
      accountEmail: 'Campaign@ac-payable.com',
      ipAddress: '192.168.1.100',
      details: 'OAuth 2.0 authorization code flow completed. Scopes: User.Read, Mail.Read, Mail.ReadWrite, Mail.Send, MailboxSettings.Read',
      success: true,
    },
    {
      id: 'log_005',
      timestamp: new Date(now - 8 * 3600 * 1000).toISOString(),
      action: 'token_refresh',
      accountEmail: 'ops@ac-payable.com',
      ipAddress: '172.16.0.22',
      details: 'Token refresh failed: refresh_token expired. User must re-authenticate.',
      success: false,
    },
    {
      id: 'log_006',
      timestamp: new Date(now - 26 * 3600 * 1000).toISOString(),
      action: 'token_expired',
      accountEmail: 'ops@ac-payable.com',
      ipAddress: '172.16.0.22',
      details: 'Refresh token expired after 90-day lifetime.',
      success: false,
    },
    {
      id: 'log_007',
      timestamp: new Date(now - 48 * 3600 * 1000).toISOString(),
      action: 'logout',
      accountEmail: 'dev@ac-payable.com',
      ipAddress: '192.168.1.55',
      details: 'User-initiated logout. Token cache cleared, MSAL accounts removed.',
      success: true,
    },
    {
      id: 'log_008',
      timestamp: new Date(now - 5 * 24 * 3600 * 1000).toISOString(),
      action: 'login',
      accountEmail: 'tracey.marion@rgbrnechanical.com',
      ipAddress: '10.0.0.45',
      details: 'First-time login. OAuth 2.0 consent granted for all requested scopes.',
      success: true,
    },
  ];
}
